[[main]]
  name = "GitHub"
  url = "https://github.com/gethyas/hyas"
  weight = 10

[[social]]
  name = "Mastodon"
  url = "https://fosstodon.org/@hyas"
  weight = 20

[[social]]
  name = "Twitter"
  url = "https://twitter.com/gethyas"
  weight = 30
